### ISSUE TITLE
Can't install mne-nirs from setup.py on Ubuntu-22.04

### ISSUE THREAD

**Issue by snowuyl** [mne-tools/mne-nirs#516]
python3 setup.py install
Traceback (most recent call last):
  File "/home/henry/samba/workspace_Python/mne-nirs/setup.py", line 7, in <module>
    from setuptools import find_packages, setup
  File "/home/henry/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 20, in <module>
    from setuptools.dist import Distribution, Feature
  File "/home/henry/.local/lib/python3.10/site-packages/setuptools/dist.py", line 35, in <module>
    from setuptools.depends import Require
  File "/home/henry/.local/lib/python3.10/site-packages/setuptools/depends.py", line 7, in <module>
    from .py33compat import Bytecode
  File "/home/henry/.local/lib/python3.10/site-packages/setuptools/py33compat.py", line 55, in <module>
    unescape = getattr(html, 'unescape', html_parser.HTMLParser().unescape)
AttributeError: 'HTMLParser' object has no attribute 'unescape'

**Comment by rob-luke** [comment]
Hi Henry, can you please not ignore the bug report template and include all the information that was requested. Specifically...

```
#### Steps to reproduce
*Replace this text with a code snippet or minimal working example [MWE] to
replicate your problem, using one of the [built-in datasets], preferably the
one called [sample]. If you can't replicate on a built-in dataset, provide also
a link to a small, anonymized portion of your data that does yield the error.*

[MWE]: https://en.wikipedia.org/wiki/Minimal_Working_Example
[built-in datasets]: https://mne.tools/dev/overview/datasets_index.html
[sample]: https://mne.tools/dev/overview/datasets_index.html#sample
```

I am closing this issue until this is reproducible. I can see that you raised lots of similar issues on many repositories
